name: Build & Release

on:
  pull_request:
    branches:
      - main
      
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Save APK
        uses: actions/upload-artifact@v2
        with:
          name: tyed-app
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Save AppBundle
        uses: actions/upload-artifact@v2
        with:
          name: tyed-appbundle
          path: build/app/outputs/flutter-apk/app-release.aab
